var dictionary = {
   'en': {
      'title': "Register",
      'login': 'Login:',
      'password': 'Password:',
      'retype_password': 'Retype password:',
      'email': "E-mail:",
      'name': "Your real name and surname:",
      'sex': "Sex:",
      'male': 'Male',
      'female': 'Female',
      'birth_date': 'Birth date',
      'login_button': 'Return to login',
      'register_button': "Register",
      'or': 'OR',
      'login_missing_error': "This field is required",
      'login_exists_error': 'This login already exists',
      'password_missing_error': 'This field is required',
      'retype_password_error': "Passwords does not match",
      'email_missing_error': "This field is required",
      'email_exists_error': 'This email is already used',
      'wrong_email_error': 'Your email is probably not valid. It must at least contain an @ symbol and something before and after it.',
      'sex_error': 'Something is wrong. Sex can be either male or female',
      'birth_date_error': 'Date is invalid',
      'January': 'January',
      'February': 'February',
      'March': 'March',
      'April': 'April',
      'May': 'May',
      'June': 'June',
      'July': 'July',
      'August': 'August',
      'September': 'September',
      'October': 'October',
      'November': 'November',
      'December': 'December',
      'other_info': 'Other info:',
      'picture': 'Picture:',
      'picture_extension_error': 'Wrong extension. Only jpeg/jpg/gif/png are allowed',
      'picture_generic_error': 'Error while uploading file. Please try another',
   },
   'ru': {
      'title': "Регистрация",
      'login': 'Логин:',
      'password': 'Пароль:',
      'retype_password': 'Повторите пароль',
      'email': "Электронная почта:",
      'name': "Ваши реальные имя и фамилия:",
      'sex': "Пол:",
      'male': 'Мужской',
      'female': 'Женский',
      'birth_date': 'Дата рождения',
      'login_button': 'Вернуться ко входу',
      'register_button': "Зарегистрироваться",
      'or': 'ИЛИ',
      'login_missing_error': "Это поле нужно заполнить",
      'login_exists_error': 'Этот логин уже существует',
      'password_missing_error': 'Это поле нужно заполнить',
      'retype_password_error': "Пароли не совпадают.",
      'email_missing_error': "Это поле нужно заполнить",
      'email_exists_error': 'Эта почта уже используется',
      'wrong_email_error': 'Возможно, Вы ошиблись. Как минимум, это поле должно содержать знак @ и что-то слева и справа.',
      'sex_error': 'Что-то не так. Пол может быть либо мужским, либо женским',
      'birth_date_error': 'Дата введена некорректно',
      'January': 'Январь',
      'February': 'Февраль',
      'March': 'Март',
      'April': 'Апрель',
      'May': 'Май',
      'June': 'Июнь',
      'July': 'Июль',
      'August': 'Август',
      'September': 'Сентябрь',
      'October': 'Октябрь',
      'November': 'Ноябрь',
      'December': 'Декабрь',
      'other_info': 'Другая информация:',
      'picture': 'Картинка:',
      'picture_extension_error': 'Некорректное расширение. Разрешены только jpeg/jpg/gif/png',
      'picture_generic_error': 'Ошибка при загрузке файла. Пожалуйста, попробуйте другой файл',
   }
};